# Generated by Django 3.1.2 on 2020-10-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201019_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student'},
        ),
    ]
